export const ADDTASK = 'ADDTASK'
export const TOGGLE_STATUS = 'TOGGLE_STATUS'
export const SORT_BY_DONE = 'SORT_BY_DONE'
export const FILTER_BY_All = 'FILTER_BY_All'
export const FILTER_BY_DONE = 'FILTER_BY_DONE'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const CHECK_ALL_DONE = 'CHECK_ALL_DONE'